name: sbip
on:
  push:
    branches:
      - 'dev/**'
      - 'release/**'
    tags:
      - 'v*'
jobs:
  push_fabric_peer_to_registry:
    name: Push Fabric Peer image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fabric repository
        uses: actions/checkout@v2
      - name: Build and push Peer to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: ${{ secrets.DOCKER_HUB_REPOSITORY_PEER }}
          dockerfile: docker/peer/Dockerfile
          tags: 1.0, 1.0.0

  push_fabric_orderer_to_registry:
    name: Push Fabric Orderer image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fabric repository
        uses: actions/checkout@v2
      - name: Build and push Orderer to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: ${{ secrets.DOCKER_HUB_REPOSITORY_ORDERER }}
          dockerfile: docker/orderer/Dockerfile
          tags: 1.0, 1.0.0
